# Generated by Django 4.0.2 on 2022-08-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='phone_num2',
        ),
    ]
