# Generated by Django 4.0.2 on 2022-06-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='product_colors',
            field=models.CharField(choices=[('GREEN', 'Green'), ('BLUE', 'Blue'), ('RED', 'Red'), ('ORANGE', 'Orange'), ('BLACK', 'Black'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('PURPLE', 'Purple'), ('BROWN', 'Brown'), ('PINK', 'Pink')], default='WHITE', max_length=10, verbose_name="product's colors"),
        ),
    ]
