# Generated by Django 4.0.2 on 2022-09-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
