# Generated by Django 4.0.2 on 2022-08-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_billingaddress_phone_num2'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_product_color',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered_product_size',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
