# Generated by Django 4.0.2 on 2022-09-16 20:05

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_wishlist_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_categories',
            field=models.CharField(max_length=255, verbose_name="product's categories"),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_colors',
            field=models.CharField(max_length=255, verbose_name="product's colors"),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sizes',
            field=models.CharField(max_length=255, verbose_name='product sizes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
