# Generated by Django 4.0.2 on 2022-06-30 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_orderitem_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
