# Generated by Django 4.0.2 on 2022-08-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderitem_ordered_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered_product_color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered_product_size',
        ),
    ]
