# Generated by Django 4.0.2 on 2022-09-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_billingaddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_order_price',
            field=models.DecimalField(decimal_places=2, max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=255, verbose_name="product's price"),
        ),
    ]
