# Generated by Django 4.0.2 on 2022-07-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_total_order_price_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
