# Generated by Django 4.0.2 on 2022-06-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_delete_addproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(null=True, verbose_name="product's price"),
        ),
    ]
