# Generated by Django 4.0.2 on 2022-07-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_order_price',
        ),
    ]
