# Generated by Django 4.0.2 on 2022-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_available',
            field=models.IntegerField(null=True, verbose_name='number available'),
        ),
    ]
