# Generated by Django 4.0.2 on 2022-08-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(choices=[], default='wewe', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[], default='wefwef', max_length=10, null=True),
        ),
    ]
