# Generated by Django 4.0.2 on 2022-06-21 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_number_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="product's id"),
        ),
    ]
