# Generated by Django 4.0.2 on 2022-06-21 19:10

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(null=True, upload_to=store.models.upload_location, verbose_name='product image 1'),
        ),
    ]
