# Generated by Django 4.0.2 on 2022-07-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order_price',
            field=models.IntegerField(null=True),
        ),
    ]
