# Generated by Django 4.0.2 on 2022-06-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_product_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_available',
            field=models.IntegerField(default=1, verbose_name='number available'),
        ),
    ]
