# Generated by Django 4.0.2 on 2022-08-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_color_alter_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[(1, 1), (2, 2)], max_length=10, null=True),
        ),
    ]
