# Generated by Django 4.0.2 on 2022-06-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_number_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_available',
            field=models.IntegerField(verbose_name='number available'),
        ),
    ]
