# Generated by Django 4.0.2 on 2022-07-11 21:11

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_billingaddress_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_countries.fields.CountryField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.country')),
            ],
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.ForeignKey(max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.city'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.country'),
        ),
    ]
