# Generated by Django 4.0.2 on 2022-07-11 22:27

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_billingaddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address1',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='address2',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='firstname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='lastname',
            field=models.CharField(default='', max_length=256),
        ),
    ]
