# Generated by Django 4.0.2 on 2022-08-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_reviews',
            field=models.IntegerField(null=True),
        ),
    ]
