# Generated by Django 4.0.2 on 2022-07-20 00:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_billingaddress_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='first_phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Phone No 1'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='second_phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Phone No 2'),
        ),
    ]
