# Generated by Django 4.0.2 on 2022-07-20 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_billingaddress_first_phone_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='first_phone_num',
            new_name='phone_num1',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='second_phone_num',
            new_name='phone_num2',
        ),
    ]
