# Generated by Django 4.0.2 on 2022-07-20 01:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('store', '0017_alter_billingaddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.customer'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_num1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Phone No 1'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_num2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Phone No 2'),
        ),
    ]
