# Generated by Django 4.0.2 on 2022-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_average_rating_product_num_of_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='num_of_visits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
