# Generated by Django 4.0.2 on 2022-07-20 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_billingaddress_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
    ]
