# Generated by Django 4.0.2 on 2022-08-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_last_visit_product_num_of_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_visits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
