# Generated by Django 4.0.2 on 2022-07-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_billingaddress_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='address2',
        ),
    ]
