# Generated by Django 4.0.2 on 2022-07-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_address1_billingaddress_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='lastname',
        ),
    ]
