# Generated by Django 4.0.2 on 2022-07-20 11:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_firstname_billingaddress_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_num1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone No 1'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_num2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone No 2'),
        ),
    ]
