# Generated by Django 4.0.2 on 2022-07-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_billingaddress_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
