# Generated by Django 4.0.2 on 2022-08-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_usersrecentlyviewedproduct_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_visit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
