# Generated by Django 4.0.2 on 2022-07-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_order_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
