# Generated by Django 4.0.2 on 2022-07-25 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session_id',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
