# Generated by Django 4.0.2 on 2022-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_order_session_id_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_order_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
