# Generated by Django 4.0.2 on 2022-09-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_wishlist_heart_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='color',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='size',
        ),
    ]
