# Generated by Django 4.0.2 on 2022-09-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_wishlist_color_remove_wishlist_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wish_item_counter',
            field=models.IntegerField(null=True),
        ),
    ]
