# Generated by Django 4.0.2 on 2022-09-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_wishlist_wish_item_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
