# Generated by Django 4.0.2 on 2022-09-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_wishlist_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
