# Generated by Django 4.0.2 on 2022-08-02 16:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_user_first_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Phone No 1'),
        ),
    ]
