# Generated by Django 4.0.3 on 2022-05-14 18:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('seller_acct', '0002_alter_vendor_acct_first_phone_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_acct',
            name='first_phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone No 1'),
        ),
        migrations.AlterField(
            model_name='vendor_acct',
            name='second_phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone No 2'),
        ),
    ]
