# Generated by Django 4.0.2 on 2022-09-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletApp', '0004_payment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
